set_property SRC_FILE_INFO {cfile:C:/Users/REV/VivadoProjects/ZYNQ_DTW/OSV_DTW_8F/OSV_DTW_8F.srcs/constrs_1/new/const1.xdc rfile:../../../OSV_DTW_8F.srcs/constrs_1/new/const1.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W8 [get_ports spi_rtl_io0_io]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports spi_rtl_io1_io]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V7 [get_ports spi_rtl_sck_io]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports spi_rtl_ss_io]
