# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/design_1_dtw_8F_32bit_0_3.xci
# IP: The module: 'design_1_dtw_8F_32bit_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xbip_dsp48_macro_0 || ORIG_REF_NAME==xbip_dsp48_macro_0} -quiet] -quiet

# IP: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/cordic_0/cordic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/blk_mem_gen_dual_256x16/blk_mem_gen_dual_256x16.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_dual_256x16 || ORIG_REF_NAME==blk_mem_gen_dual_256x16} -quiet] -quiet

# IP: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/blk_mem_gen_32x256/blk_mem_gen_32x256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_32x256 || ORIG_REF_NAME==blk_mem_gen_32x256} -quiet] -quiet

# XDC: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/blk_mem_gen_dual_256x16/blk_mem_gen_dual_256x16_ooc.xdc

# XDC: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/blk_mem_gen_32x256/blk_mem_gen_32x256_ooc.xdc

# IP: C:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/design_1_dtw_8F_32bit_0_3.xci
# IP: The module: 'design_1_dtw_8F_32bit_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xbip_dsp48_macro_0 || ORIG_REF_NAME==xbip_dsp48_macro_0} -quiet] -quiet

# IP: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/cordic_0/cordic_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/blk_mem_gen_dual_256x16/blk_mem_gen_dual_256x16.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_dual_256x16 || ORIG_REF_NAME==blk_mem_gen_dual_256x16} -quiet] -quiet

# IP: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/blk_mem_gen_32x256/blk_mem_gen_32x256.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_32x256 || ORIG_REF_NAME==blk_mem_gen_32x256} -quiet] -quiet

# XDC: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/blk_mem_gen_dual_256x16/blk_mem_gen_dual_256x16_ooc.xdc

# XDC: c:/Users/REV/VivadoProjects/ZYNQ_DTW/dtw_mtds_comparison/mtds_demo_1.srcs/sources_1/bd/design_1/ip/design_1_dtw_8F_32bit_0_3/src/blk_mem_gen_32x256/blk_mem_gen_32x256_ooc.xdc
